[package]
name = "daytape"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
directories = "4"
serde = { version = "1", features = ["derive"] }
termbuffer = "0.1"
serde_yaml = "0.8"
